// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npqayykcyyynyrnmnoif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wcWF5eWtjeXl5bnlybm1ub2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODM0NzQsImV4cCI6MjA2NDQ1OTQ3NH0.PYgN4cq0ixvOx8zVrJ7KFZgj3Md38flHtT7Zl66E7l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);